### ISSUE TITLE
Training models - Adam_1 not found in checkpoint?

### ISSUE THREAD

**Issue by GenTxt** [FrancescoSaverioZuppichini/LSTM-Text-Generator#2]
Hi:

Thanks for the cool repo. I've tested your supplied Shakespeare and bible models and they work 100%
in ubuntu 16.04 and tf 1.4 with 1070 gpu.

I can train new models but when I try to generate I get this error:

NotFoundError (see above for traceback): Key rnn/multi_rnn_cell/cell_2/lstm_cell/kernel/Adam_1 not found in checkpoint

What's strange is that during training the sample output appears in the terminal after each epoch. 
There's no indication of a problem.

Is there anything I can change in the code to fix this? 

Thanks

**Comment by FrancescoSaverioZuppichini** [comment]
Hi there,

first of all, sorry for the messy code! It was for an assignment :)

It seems that operation was not found in the checkpoint. Can you provide me an example how you are calling the command line? 

Have a nice day

Francesco

**Comment by GenTxt** [comment]
Hi Francesco:

Yes. I've retrained the model 3 times and it's always the same error.

Your shakespeare model works 100% and generates output

Again it's strange that it shows the sampled text after each epoch in the
terminal but it won't generate from saved model.

Thanks

**Comment by FrancescoSaverioZuppichini** [comment]
It was for debugging. I will check as soon as I have time ;)

**Comment by FrancescoSaverioZuppichini** [comment]
I know why, I hardcoded the model params here 

https://github.com/FrancescoSaverioZuppichini/LSTM-Text-Generator/blob/master/core/model/generate.py

 because I was lazy to read how to fetch them from the restored graph, do you know how to do that?

**Comment by GenTxt** [comment]
Thanks for the quick reply.

Sorry, I don't know how to restore from the saved graph.

Just checked your github repo. Will these new changes solve the issue?

Thanks

**Comment by GenTxt** [comment]
Downloaded your latest version.

Unfortunately cannot generate from your original models (similar error as
below).

Training also generates this error which did not happen before.

python3 main.py --train=True --file='data/corpus' --layers=512,512

Loading corpus.txt

Traceback (most recent call last):
  File "main.py", line 9, in <module>
    train_model(args)
  File "/home/pixelhead/Desktop/LSTM-Text-Generator/core/model/train.py",
line 38, in train_model
    pred,preds, cost, train_step, accuracy = my_model.build()
  File "/home/pixelhead/Desktop/LSTM-Text-Generator/core/model/model.py",
line 124, in build
    loss = self.get_loss(output_linear)
  File "/home/pixelhead/Desktop/LSTM-Text-Generator/core/model/model.py",
line 85, in get_loss
    loss = tf.nn.softmax_cross_entropy_with_logits_v2(logits=logits,
labels=y_flat)

AttributeError: module 'tensorflow.python.ops.nn' has no attribute
'softmax_cross_entropy_with_logits_v2'

**Comment by FrancescoSaverioZuppichini** [comment]
Yes, you need to update to tf 1.5. So you don't know how to directly get variables from a restored graph?

**Comment by GenTxt** [comment]
It appears I need cuda 9.0 also? Installing next to cuda 8.0

Also installing tf 1.5.

Is there anyway to modify your original code or generate my own models with
your hardcoded parameters?

That would work for me using a command line example.

Sorry, but I'm new to python/tensorflow and I'm unclear how to directly get
variables from a restored graph.

**Comment by FrancescoSaverioZuppichini** [comment]
Okay, then let me use a workaround until I fix it. You will need to also input the EXACT layers u used for training, so layers.

```
python3 main.py --generate=True ... layers=<THE_LAYERS_YOU_USED>

```

**Comment by GenTxt** [comment]
Thanks for looking into this solution.

T 1.5 and cuda 9 are not working well. :(

Returning to 1.4

**Comment by GenTxt** [comment]
Working now in tf 1.4, cuda 8 using workaround code changes and original archive.

Cheers

**Comment by FrancescoSaverioZuppichini** [comment]
perfect ;)
